stages:
  - rules

check_format:
  stage: rules
  image: node:latest
  script:
    - cd ./backend
    - npm install
    - npm run check_format

lint:
  stage: rules
  image: node:latest
  script:
    - cd ./backend
    - npm install
    - npm run lint
