stages:
  - build
  - rules
  - push

image: docker:20.10.7

services:
  - docker:20.10.7-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG ./backend
    - docker push $IMAGE_TAG

check_format:
  stage: rules
  script:
    - docker pull $IMAGE_TAG
    - docker run --entrypoint '/bin/sh' $IMAGE_TAG -c 'npm run check_format'
  allow_failure: true

lint:
  stage: rules
  script:
    - docker pull $IMAGE_TAG
    - docker run --entrypoint '/bin/sh' $IMAGE_TAG -c 'npm run lint'

push:
  stage: push
  variables:
    IMAGE_TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker pull $IMAGE_TAG
    - docker rename $IMAGE_TAG $IMAGE_TAG_BRANCH
    - docker push $IMAGE_TAG_BRANCH
  only:
    - develop
    - main
