version: '3'
services:
  nginx:
    build: ./nginx
    image: $CI_REGISTRY_IMAGE/nginx:latest
    container_name: nginx-proxy
    hostname: nginx-proxy 
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend: 
    build: ./frontend
    image: $CI_REGISTRY_IMAGE/frontend:latest
    container_name: crisp-frontend
    depends_on: 
      - backend
    environment:
      - PORT=3000
    ports:
      - "3000"
    restart: always
  backend:
    build: ./backend
    image: $CI_REGISTRY_IMAGE/backend:latest
    container_name: crisp-backend
    environment:
      - PORT=4000
      - MONGODB_URI=$CD_MONGODB_URI
      - JWT_SECRET=$CD_JWT_SECRET
      - JWT_EXPIRE=$CD_JWT_EXPIRE
    ports:
      - "4000"
    restart: always