version: '3'
services:
  nginx:
    build: ./nginx
    image: crisp_nginx:latest
    container_name: nginx-proxy
    hostname: nginx-proxy 
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend: 
    build: ./frontend
    image: crisp_frontend:latest
    container_name: crisp-frontend
    depends_on: 
      - backend
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_URL=/api
    ports:
      - "3000"
    restart: always
  backend:
    build: ./backend
    image: crisp_backend:latest
    container_name: crisp-backend
    environment:
      - PORT=4000
      - MONGODB_URI=$MONGODB_URI
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRE=$JWT_EXPIRE
      - AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
      - AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET=$AWS_S3_BUCKET
    ports:
      - "4000"
    restart: always