version: '3'
services:
  nginx:
    image: nginx:1.21.1
    container_name: nginx-proxy
    hostname: nginx-proxy 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend: 
    build: ./frontend
    image: $CI_REGISTRY_IMAGE/frontend:latest
    container_name: crisp-frontend
    depends_on: 
      - backend
    environment:
      - PORT=$FRONTEND_PORT
    ports:
      - "$FRONTEND_PORT"
    restart: always
  backend:
    build: ./backend
    image: $CI_REGISTRY_IMAGE/backend:latest
    container_name: crisp-backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=$BACKEND_PORT
    ports:
      - "$BACKEND_PORT"
    restart: always