version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    hostname: nginx-proxy 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  frontend: 
    build: ./frontend
    container_name: crisp-frontend
    depends_on: 
      - backend
    environment:
      - PORT=$FRONTEND_PORT
    ports:
      - "3000:$FRONTEND_PORT"
    restart: always
  backend:
    build: ./backend
    container_name: crisp-backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=$BACKEND_PORT
    ports:
      - "4000:$BACKEND_PORT"
    restart: always